
const SAGA_EXTRAC_TEXT_FROM_IMAGE = 'SAGA_EXTRAC_TEXT_FROM_IMAGE';
const EXTRAC_TEXT_FROM_IMAGE = 'EXTRAC_TEXT_FROM_IMAGE';
 
export let constants =
{
    SAGA_EXTRAC_TEXT_FROM_IMAGE: SAGA_EXTRAC_TEXT_FROM_IMAGE,
    EXTRAC_TEXT_FROM_IMAGE: EXTRAC_TEXT_FROM_IMAGE
}
