export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const IS_LOADING = 'IS_LOADING';

/* handle by saga */
export const LOAD_CURRENT_USER_REQUEST = 'LOAD_CURRENT_USER_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';

export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const SHOW_LOADING = 'SHOW_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';