
const SAGA_GET_LIST_TK_NO_THUE = 'SAGA_GET_LIST_TK_NO_THUE';
const GET_LIST_TK_NO_THUE = 'GET_LIST_TK_NO_THUE';
 
export let constants =
{
    SAGA_GET_LIST_TK_NO_THUE: SAGA_GET_LIST_TK_NO_THUE,
    GET_LIST_TK_NO_THUE: GET_LIST_TK_NO_THUE
}
